// utils/blogData.js
export const BLOG_POSTS = [
   {   
     id: 118,
    title: '    AI ئېيجېنت دېگەن نېمە؟ ھاسىللىغۇچ AI دىن قانداق پەرق قىلىدۇ؟     ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 98',
    category: '         سۇنئي ئەقىل ۋاكالەتچى       ',
    tags: ['  سۇنئي ئەقىل ۋاكالەتچى ', ' ئىلىم  ', '  سۇنئي ئەقىل ', '   ئىنسانىيەت '],
    image: 'https://media.licdn.com/dms/image/v2/D4E12AQHdDCHQH8ScbQ/article-cover_image-shrink_720_1280/B4EZbegSkoHcAI-/0/1747489732845?e=2147483647&v=beta&t=vFlFZYKAB1TvaLFXOewVzmBe4waVmkWTr4qjpEzE4rw',
    summary: '       ChatGPT ياكى Gemini قاتارلىق ھاسىللىغۇچ AI لارنى كۆپلەر ئىشلىتىپ كېلىۋاتىدۇ. شۇنداق بولسا، AI ئېيجېنت نېمە بىلەن پەرق قىلىدۇ؟',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog118'
  },
  {   
     id: 117,
    title: '    AI ۋاكالەتچى (Agent)  قۇرۇش ئۇسۇلى    ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 98',
    category: '         سۇنئي ئەقىل ۋاكالەتچى       ',
    tags: ['  سۇنئي ئەقىل ۋاكالەتچى ', ' ئىلىم  ', '  سۇنئي ئەقىل ', '   ئىنسانىيەت '],
    image: 'https://static.vecteezy.com/system/resources/thumbnails/061/902/803/small/ai-chatbot-ai-assistant-with-cyborg-woman-head-surrounded-by-connected-gears-and-technology-icons-ai-agent-concept-of-artificial-intelligence-automation-and-machine-learning-illustration-vector.jpg',
    summary: '         «سىزنىڭ شەخسىي سۈنئىي ئەقىل ياردەمچىڭىز. ھەر قانداق مەشغۇلات سىستېمىسى. ھەر قانداق سۇپا. ئومۇرتقا يولى. 🦞» ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog117'
  },
  {   
     id: 116,
    title: '    AI ۋاكالەتچى (Agent) دېگەن نىمە    ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 98',
    category: '         سۇنئي ئەقىل ۋاكالەتچى       ',
    tags: ['  سۇنئي ئەقىل ۋاكالەتچى ', ' ئىلىم  ', '  سۇنئي ئەقىل ', '   ئىنسانىيەت '],
    image: 'https://static.wixstatic.com/media/9aabdb_1ae27b0f28394da8aee0891959e19621~mv2.gif',
    summary: '         «سىزنىڭ شەخسىي سۈنئىي ئەقىل ياردەمچىڭىز. ھەر قانداق مەشغۇلات سىستېمىسى. ھەر قانداق سۇپا. ئومۇرتقا يولى. 🦞» ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog116'
  },
  {   
     id: 115,
    title: '   AI ۋاكالەتچى (Agent)      ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 98',
    category: '         سۇنئىي ئەقىل ۋاكالەتچى       ',
    tags: ['  سۇنئىي ئەقىل ۋاكالەتچى ', ' ئىلىم  ', '  سۇنئىي ئەقىل ', '   ئىنسانىيەت '],
    image: 'https://media.licdn.com/dms/image/v2/D4D12AQElWGlsGaGD4g/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1733323455884?e=2147483647&v=beta&t=l_1sgsxfguAamayw7UGRa4rl58gjoevbbHuKws30WlM',
    summary: '          «بۇنى بىلمىسەك خەتەرلىك! سۈنئىي ئەقىل ئاگېنتى دېگەن نېمە؟ ئادەتتىكى سۈنئىي ئەقىلدىن قانداق پەرقلەيدۇ؟» ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog115'
  },
  {   
     id: 114,
    title: '   نىسپىلىك نەزەرسىيەسى    ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 98',
    category: '              كائىنات ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://cdn.theatlantic.com/thumbor/jUgX_yr_mrNGumci7lCH6kNU2Yw=/0x50:960x590/960x540/media/img/mt/2016/02/einstein_waves/original.gif',
    summary: '           قارا ئۆڭكۈرلەرنىڭ ئىچىدە نىمىلەر بولىدىغانلىقىنى چۈشەندۈرۈش ئۈچۈن، ئالىملار يېقىندا بىر ئاسان چۈشىنىلىدىغان مودېلنى تەكشىلەپ چىقتى.   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog114'
  },
  {   
     id: 113,
    title: '   قارا ئۆڭكۈرلەرنىڭ قانداق ئىشلەيدىغانلىقىنىڭ ئاسان چۈشىنىلىدىغان چۈشەندۈرۈشى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 98',
    category: '              كائىنات ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://chandra.harvard.edu/photo/2013/casa/casa_comparison.gif',
    summary: '           قارا ئۆڭكۈرلەرنىڭ ئىچىدە نىمىلەر بولىدىغانلىقىنى چۈشەندۈرۈش ئۈچۈن، ئالىملار يېقىندا بىر ئاسان چۈشىنىلىدىغان مودېلنى تەكشىلەپ چىقتى.   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog113'
  },
  {   
     id: 112,
    title: '    كىۋانىت تۇتاشلىقى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 118',
    category: '           مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://miro.medium.com/v2/resize:fit:1280/1*1n4WOBKeNPsVvCUB-nTW9Q.gif',
    summary: '         ئارىلىرى چەكسىز بولغان قۇبىتلارنىڭ بىر-بىرىگە باغلىنىشى   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog112'
  },
  {   
     id: 111,
    title: '     كىۋانىت سۇپېرپوزىتسىيىسى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 118',
    category: '           كىۋانىت مېخانىكىسى ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  سۇنئى ئەقىل ', '   كىۋانىت '],
    image: 'https://images.steamusercontent.com/ugc/791983060743498943/4F8FCDF048457B1094DBF13CF2BB14FD6C04969B/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false',
    summary: '          بىر ۋاقىتتا بارلىق ھالەتلەردە بولۇش   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog111'
  },
  {   
     id: 110,
    title: '    2026-يىل: «AI ئاگېنتلىرى» نىڭ يىلتىز تارتىدىغان يىلى',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 118',
    category: '           مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://assets.st-note.com/production/uploads/images/241551878/rectangle_large_type_2_7468f8715efd682ffdf6732f5909c786.png?width=1280',
    summary: '           تېخنولوگىيە تەرەققىي قىلغانسېرى، بالىلار بىلەن ئاسانلىق سۆزلىشىدىغان CLOiD قاتارلىق روبوتلار ئۆزىنىڭ ئورنىنى تېپىشقا باشلىدى.   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog110'
  },
   {   
     id: 109,
    title: '     🤖 ؟ AI ۋاكالەتچى (Agent) دېگەن نىمە',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 118',
    category: '           مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://viscovery.com/wp-content/uploads/2024/08/AI-Agentic-Workflow-Banner.webp',
    summary: '           تېخنولوگىيە تەرەققىي قىلغانسېرى، بالىلار بىلەن ئاسانلىق سۆزلىشىدىغان CLOiD قاتارلىق روبوتلار ئۆزىنىڭ ئورنىنى تېپىشقا باشلىدى.   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog109'
  },
  {   
     id: 108,
    title: '      AI بىلەن دوستلۇق: بالىلار روبوت بىلەن دوست بولالايدۇمۇ؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 118',
    category: '           مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://www.eai4kids.com/how_robots_are_shaping_early_learning.png',
    summary: '           تېخنولوگىيە تەرەققىي قىلغانسېرى، بالىلار بىلەن ئاسانلىق سۆزلىشىدىغان CLOiD قاتارلىق روبوتلار ئۆزىنىڭ ئورنىنى تېپىشقا باشلىدى.   ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog108'
  },
  {   
     id: 107,
    title: '       سۈنئىي ئەقىل بىلەن سۆزلىشىش — بەلكىم بىزنىڭ بالىلىرىمىزنىڭ تۇنجى تىلى؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 107',
    category: '         باللار  ۋە مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://cheqdin.com/storage/AI_Early_Years_Childcare_Cheqdin.jpeg',
    summary: '           بالىلار ChatGPT بىلەن سۆزلىشىپ چوڭ بولىدۇ. بۇ ئۇلارنىڭ تىل رىۋاجىغا، مۇناسىۋىتىگە، ھەتتا ئويلىشىش ئۇسلۇبىغا قانداق تەسىر كۆرسىتىدۇ؟ ',
    likes: 194,
    comments: 5,
    views: 1790,
    component: 'Blog107'
  },
  {   
     id: 106,
    title: '  كىم بۇ ماشىنىنىڭ قانۇنىنى يازىدۇ؟  سۈنئىي ئەقىلنىڭ ئەخلاقىي قانۇنى:',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 106',
    category: '      دىنىيەت  ۋە فەلسەپە ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://img.freepik.com/premium-photo/ai-ethics-ai-law-concept-developing-ai-codes-ethics_592076-3144.jpg',
    summary: '           AI نىڭ قارارى خاتا بولۇپ، بىر كىشى زىيان كۆرگەندە، مەسئۇل كىم؟ ئىشلەپچىقارغۇچى؟ قوللىنىشچى؟ ياكى AI ئۆزى؟ ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog106'
  },
  {   
     id: 105,
    title: '      2030-يىلىدىكى «سىزنىڭ بالىڭىز» نېمە ئۆگىنىدۇ؟  سۈنئىي ئەقىل مەكتىپى:',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 105',
    category: '      دىنىيەت  ۋە فەلسەپە ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://media.licdn.com/dms/image/v2/D5622AQGzYcNOeqtgVQ/feedshare-shrink_800/B56ZQqoOIEHQAg-/0/1735881994133?e=2147483647&v=beta&t=iBpmNc96bXMcNmYMFCKOtj9ELiilT84hD3vVsSA4JIk',
    summary: '            بىلىم ئەمەس، بەلكى «قارار چىقىرىش»، «مۇھاكىمە»، «مۇناسىۋەت قۇرۇش» ئۆگىتىلىدۇ ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog105'
  },
  {   
     id: 104,
    title: '    بىزنىڭ ئويلىشىش قابىلىيتىمۇ «ئاپتوماتىك» بولۇپ قالامدۇ؟   سۈنئىي ئەقىل بىلەن ئويلىشىش ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 104',
    category: '      دىنىيەت  ۋە فەلسەپە ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://static.wixstatic.com/media/3cd83b_c84cd20ab5154391a48b4940cf0157e0~mv2.gif',
    summary: '             ھەر قانداق سوئالغا جاۋاب تېپىش ئادەتتە بولۇپ قالغاندا، بىز «سوئال قويۇش» نى ئۇنتۇپ قالامدۇ؟  ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog104'
  },
  {   
     id: 103,
    title: '       فىزىكىلىق سۈنئىي ئەقىل ۋە دىنى:\nماشىنا «ئىمان» غا ئىگە بولالايدۇمۇ؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '      دىنىيەت  ۋە فەلسەپە ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmJW_oa_LlJdGjXIzMFr04WWoHfM6qUl3ToA&s',
    summary: '             بۇ تېما ئەخلاق، فەلسەپە، دىن ۋە تېخنىكا ئوتتۇرىسىدىكى چەكلىك سۇغۇرمانى بوزىدۇ.  ',
    likes: 192,
    comments: 5,
    views: 1790,
    component: 'Blog103'
  },
  {   
     id: 102,
    title: '        بالىلارغا فىزىكىلىق سۈنئىي ئەقىلنى قانداق چۈشەندۈرۈش كېرەك؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '    باللار  ۋە مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/677e77445851c5001d912919.jpg',
    summary: '             بالىلار «سۈنئىي ئەقىل» دېگەن سۆزنى ئاڭلىغاندا، كۆپىنچىسى «ئېكران ئىچىدىكى سۆزلەيدىغان ماشىنا» دەپ ئويلايدۇ. لېكىن 2026-يىلى، سۈنئىي ئەقىل ھازىر ئېكراندىن چىقىپ كەتتى!    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog102'
  },
   {   
    id: 101,
    title: '          بالىلارغا فىزىكىلىق سۈنئىي ئەقىلنى قانداق چۈشەندۈرۈش كېرەك؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '    باللار  ۋە مائارىپ ',
    tags: ['  كەلگۈسى', ' ئىلىم  ', '  مائارىپ ', '   باللار '],
    image: 'https://img.freepik.com/free-photo/cartoon-ai-robot-scene_23-2151675072.jpg?semt=ais_hybrid&w=740&q=80',
    summary: '              بالىلار «سۈنئىي ئەقىل» دېگەن سۆزنى ئاڭلىغاندا، كۆپىنچىسى «ئېكران ئىچىدىكى سۆزلەيدىغان ماشىنا» دەپ ئويلايدۇ. لېكىن 2026-يىلى، سۈنئىي ئەقىل ھازىر ئېكراندىن چىقىپ كەتتى!    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog101'
  },
   {   
    id: 100,
    title: '           7-قىسىم (ئاخىرقى قىسىم): نېمە ئۈچۈن ئىنسانلار يەنىلا داۋالاش ۋە مائارىپنى ئېلىپ بېرىشى كېرەك؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '    مېدىتسىنا  ۋە مائارىپ ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://aka-link.net/wp-content/uploads/2024/02/seiseiai-dx-kaigaijirei02.jpg',
    summary: '              فيزيكىلىق سۈنئىي ئەقىل — بۇ خىزمەتلەرنى يوقىتىش ئەمەس، بەلكى ئىنسان بولۇشنىڭ مەنىسىنى قايتا كۆتۈرۈش.   ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog100'
  },
   {   
    id: 99,
    title: '           6-قىسىم: توختىتىلىدىغان ئىنسان بولۇش',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   كۋانت مېخانىكىسى ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://www.pro.logitec.co.jp/about_hdd/hddssd/20200904/images/main.jpg',
    summary: '              فيزيكىلىق سۈنئىي ئەقىل دەۋرىدە، سۈنئىي ئەقىل ھەقىقىي دۇنيادا ھەرىكەت قىلىدۇ: روبوتلار ئىشلەيدۇ، ماشىنىلار ھەيدىلىدۇ، دىئاگنوز قويۇلىدۇ. بۇ ھەرىكەتلەرنىڭ ھەممىسى بىر سوئالنى تۇغدۇرىدۇ:    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog99'
  },
   {   
    id: 98,
    title: '           5-قىسىم: خىزمەتلەر يوقىلىپ كېتەمدۇ ياكى ئۆزگىرەمدۇ؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '    خىزمەت ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://vinciai.academy/wp-content/uploads/2024/06/stem_and_AI_education_with_professional_experts_from_the_universities-768x768.png',
    summary: '             ئىي ئەقىل بارلىق خىزمەتلەرنى يوقىتىدۇ» دېگەن خەۋەرلەر ھەر يىلى يېڭىدىن يېڭىغا چىقىدۇ. لېكىن 2026-يىلنىڭ باشىدا CES 2026، NVIDIA، Boston Dynamics قاتارلىق تەجرىبىلەر بىزگە بىر نەرسىنى ئېنىق كۆرسىتتى:   ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog98'
  },
   {   
    id: 97,
    title: '           4-قىسىم: فىزىكىلىق سۈنئىي ئەقىل دەۋرىدە قايتا ئۆگىنىش',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   كۋانت مېخانىكىسى ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://www.unite.ai/wp-content/uploads/2022/03/ai-education-tools.png',
    summary: '             CES 2026 دا، NVIDIA نىڭ «Alpamayo» سىستېمىسى، LG نىڭ «CLOiD» روبوتى، Boston Dynamics نىڭ «Atlas» روبوتى — بۇلارنىڭ ھەممىسى بىر نەرسىنى كۆرسىتىدۇ: فيزيكىلىق سۈنئىي ئەقىل ھازىر «ئېكران ئىچىدە» ئەمەس، بەلكى «ھەقىقىي دۇنيادا» ئىشلەيدۇ.    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog97'
  },
   {   
    id: 96,
    title: '          3-قىسىم: مائارىپ ئەمدى «ئوقۇتۇش ئورنى» ئەمەس',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   مائارىپ  ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://www.forwardpathway.com/wp-content/uploads/2025/09/AI_Education_Ethics_Challenges_Future.jpg',
    summary: '             نېمە ئۈچۈن مائارىپ سۈنئىي ئەقىلنى بىر قەدەم ئارقىغا قويۇپ، «ھۆكۈم چىقىرىشنى تەربىيەلەش» يولىغا كىردى؟    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog96'
  },
   {   
    id: 95,
    title: '         2-قىسىم: سۈنئىي ئەقىل دىئاگنوزى قويۇش قارارىنى كىم چىقىرىدۇ؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '    سۇنئي ئەقىل ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://assets.st-note.com/production/uploads/images/243186036/rectangle_large_type_2_8a5e0b9261bc0723e262a6982a56ce90.jpg?width=800',
    summary: '              سۈنئىي ئەقىل بىر پاتسىيەنتنىڭ CT رەسىمىنى كۆرۈپ: «بۇ يەردىكى تۈگۈن %92 ئېھتىماللىق بىلەن زەڭگىن بىخاسىرەت» دەيدۇ. بۇ جاۋاب ناھايىتى دەقتىك. لېكىن بۇ جاۋاب — دىئاگنوز ئەمەس. بۇ تەخمىن.   ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog95'
  },
   {   
    id: 94,
    title: '           1-قىسىم: نېمە ئۈچۈن داۋالاش مائارىپى سۈنئىي ئەقىل دەۋرىدە ئارقىدا قالدى؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '    تىبابەت ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://assets.st-note.com/production/uploads/images/243936435/rectangle_large_type_2_c12ed6b46e8423ca34c704d1c9450ca6.jpg?width=1280',
    summary: '             سۈنئىي ئەقىل تېببىي ساھەدە تېز سۈرئەتتە يېتىلىۋاتىدۇ. دىئاگنوز ياردەمچىلىكى، رادىئوگرافىيە تەھلىلى، پاتسىيەنت خاتىرىلىرىنى ئاپتوماتىكلاشتۇرۇش، ھەتتا روبوت ئوپېراتسىيەسى قاتارلىقلار ھازىر دۇنيانىڭ كۆپ دۆلەتلىرىدە رېئاللىققا ئايلىنىپ قالدى   ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog94'
  },
   {   
    id: 93,
    title: '           ئۇنىۋېرسىتېت مائارىپى ۋە سۈنئىي ئەقىلدىن كېلىپ چىققان بىر سوئال ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '     مائارىپ ',
    tags: ['  سۇنئي ئەقىل', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://assets.st-note.com/production/uploads/images/243851704/rectangle_large_type_2_6842e328ae52b13f345df6d9f5c6d414.jpg?width=1280',
    summary: '[باشلىنىش] ئۇنىۋېرسىتېت مائارىپى ۋە سۈنئىي ئەقىلدىن كېلىپ چىققان بىر سوئال: فىزىكىلىق سۈنئىي ئەقىل دەۋرىدە تېببىي ۋە مائارىپ قەيەرگە قاراپ ماڭىدۇ؟    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog93'
  },
   {   
    id: 92,
    title: '        CES 2026 فىزىكىلىق سۈنئىي ئەقىل دەۋرىنىڭ يېتىپ كېلىشىنى كۆرسىتىپ بېرىدۇ   ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   كۋانت مېخانىكىسى ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://assets.st-note.com/production/uploads/images/242907803/rectangle_large_type_2_4402ae6204dd6901ad55fddff5f9c0bd.png?width=4000&height=4000&fit=bounds&format=jpg&quality=90',
    summary: '               CES 2026 فىزىكىلىق سۈنئىي ئەقىل دەۋرىنىڭ يېتىپ كېلىشىنى كۆرسىتىپ بېرىدۇ: ئېكراندىن ھەقىقىي دۇنياغا سەكرەۋاتقان سۈنئىي ئەقىل ئىنقىلابى    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog92'
  },
  {   
    id: 91,
    title: '            ۋون نېيمان زەنجىرى ۋە «ئاڭ» ئۇقۇمىنىڭ كۋانت مېخانىكىسىدىكى ئورنى نېمە؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   كۋانت مېخانىكىسى ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://i.pinimg.com/originals/a3/5b/be/a35bbe0fb22c2522be857c07e492575b.gif',
    summary: '               ۋون نېيمان زەنجىرى ۋە «ئاڭ» ئۇقۇمىنىڭ كۋانت مېخانىكىسىدىكى ئورنى نېمە؟     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog91'
  },
  {   
    id: 90,
    title: '                نېمىشقا ئۆتمۈشنى ئېسىمىزدە تۇتىمىز، ئەمما كەلگۈسىنى ئېسىمىزدە تۇتمايمىز؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   ۋاقىت ',
    tags: ['  ۋاقىت', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://scitechdaily.com/images/Abstract-Time-Symmetry-Concept.gif',
    summary: '                 نېمىشقا ئۆتمۈشنى ئېسىمىزدە تۇتىمىز، ئەمما كەلگۈسىنى ئېسىمىزدە تۇتمايمىز؟     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog90'
  },
  {   
    id: 89,
    title: '               «ۋاقىت» كۋانت تارتىش كۈچى نەزەرىيىسىدە مەۋجۇت ئەمەس دېگەن نېمە؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   كۋانت تارتىش كۈچى ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   كۋانت تارتىش كۈچى '],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr2rFImKKKwSSBpgLn4Nz24e8YTU06foQYFw&s',
    summary: '            «ۋاقىت» كۋانت تارتىش كۈچى نەزەرىيىسىدە مەۋجۇت ئەمەس دېگەن نېمە؟     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog89'
  },
  {   
    id: 88,
    title: '       ھاۋكىڭ رادىئاتسىيەسىنىڭ فىزىكىسى توغرىسىدىكى كۆپ ئۇچرايدىغان خاتا قاراشلار',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '   فىزىكا ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   فىزىكا '],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxU-_O0ap6MagTU3aEVkKTpDCSKdIGyMjgQg&s',
    summary: '                ھاۋكىڭ رادىئاتسىيەسىنىڭ فىزىكىسى توغرىسىدىكى كۆپ ئۇچرايدىغان خاتا قاراشلار     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog88'
  },
   {   
    id: 87,
    title: '  نىرۋا تورى ۋە ئۆزگەرتكۈچ مودېلى — مۇكەممەل دەرسلىك ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  نىرۋا تورى ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://miro.medium.com/v2/resize:fit:1400/1*4Ky7WD2Bwt7ONuewCEimbg.gif',
    summary: '   نىرۋا تورى ۋە ئۆزگەرتكۈچ مودېلى — مۇكەممەل دەرسلىك      ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog87'
  },
  {   
    id: 86,
    title: '  نىيوتون فىرىكىسى  كىچىك بالىلار ئۈچۈن ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  فىزىكا ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://i.pinimg.com/originals/fc/4a/4a/fc4a4a329269e36c4751e4170634cdc2.gif',
    summary: '   نىيوتون فىرىكىسى  كىچىك بالىلار ئۈچۈن      ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog86'
  },
  {   
    id: 85,
    title: '  كۋانتۇم فىزىكىسى — مۇكەممەل دەرسلىك',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   كىۋانىت '],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKrQd69nCDoFKeIYFC3CdxZmyS-LKQ-IGA1w&s',
    summary: '   كىۋانىت دەرسلىك باشلانغۇچلار ئۈچۈن      ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog85'
  },
  {   
    id: 84,
    title: '  ئومۇمىي نىسبىيەت نەزەرىيىسى كىچىك بالىلار ئۈچۈن ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  فىزىكا ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://imagine-public.x.ai/imagine-public/images/a0d93cde-c6c4-47d6-a19a-ce4d57c8e009.jpg',
    summary: '   ئومۇمىي نىسبىيەت نەزەرىيىسى كىچىك بالىلار ئۈچۈن      ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog84'
  },
  {   
    id: 83,
    title: ' بىرلا ۋاقىتتا ئىككى ئورۇندا بولۇش: كىۋانىت پاراللىقلىقنى چۈشەندۈرۈش ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   كىۋانىت '],
    image: 'https://miro.medium.com/v2/resize:fit:1400/1*4ERql28cfij2OOzoVOsP3g.gif',
    summary: '   بىرلا ۋاقىتتا ئىككى ئورۇندا بولۇش: كىۋانىت پاراللىقلىقنى چۈشەندۈرۈش      ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog83'
  },
  {   
    id: 82,
    title: ' كىۋانىت فىزىكىسى كىچىك بالىلار ئۈچۈن ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   كىۋانىت '],
    image: 'https://imagine-public.x.ai/imagine-public/images/067ec460-2881-44e9-8cef-8230938ed726.jpg',
    summary: ' كىۋانىت فىزىكىسى كىچىك بالىلار ئۈچۈن      ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog82'
  },
  {   
    id: 81,
    title: ' ئەسلى سۈنئىي ئەقىل: سۈنئىي ئەقىل 2026-يىلى قانداق تەرەققىي قىلىدۇ؟',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئۆلچەم ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://protrude.com/uploads/2025/07/ai2026problem-thumbnail-1000x525.jpg',
    summary: '  ئەسلى سۈنئىي ئەقىل ئۆتكەن بىر قانچە يىلدا بارغانسېرى ئەقىللىق بولۇپ قالدى، ئەمما ئۇنىڭ نېمە قىلالايدىغانلىقىلا ئەمەس، بەلكى بىزنىڭ ئۇنىڭغا قانداق مۇئامىلە قىلىدىغانلىقىمىزمۇ ئۆزگىرىشى مۇمكىن.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog81'
  },
  {   
    id: 80,
    title: ' ئۆلچەم دېگەن نېمە؟ رېئاللىق قانچە ئۆلچەمدىن تەركىب تاپىدۇ؟ ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئۆلچەم ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '   ئىنسانىيەت '],
    image: 'https://media3.giphy.com/media/v1.Y2lkPTZjMDliOTUyaWZqdXE0c2xuOWFiczBrY3g3M2U5c2h0MTk4bm1tbDBsZmU4OG1waCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/AvCPKNLbH6FoI/200.gif',
    summary: '  كۈندىلىك تۇرمۇشىمىزدا بىز دائىم «باشقا سەۋىيەدىكى قابىلىيەت» ياكى «ئىككى ئۆلچەملىك پېرسوناژلارنىڭ مەستانىسى» دېگەندەك سۆزلەرنى ئىشلىتىمىز. قانداقلا بولمىسۇن، «ئۆلچەم» ئەمەلىيەتتە ماتېماتىكا ۋە فىزىكىدا ئىنتايىن مۇھىم ۋە چوڭقۇر ئۇقۇم. بىز ھەر كۈنى ئادەتتىكىدەك ئىشلىتىدىغان بۇ سۆزنىڭ ئارقىسىدا، بىز ھېس قىلىدىغان دۇنيانىڭ ئاساسى ياتىدۇ.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog80'
  },
  {   
    id: 79,
    title: '  ھىگگىس بوزونى ھەققىدە  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://media3.giphy.com/media/v1.Y2lkPTZjMDliOTUyZHp2YnRyZm9rejNkNGU1bnd4b3RsNGJ2NGJwMXQzbXRsb2FpaGo4cSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/m9Y5EzlLctzGctrNLm/source.gif',
    summary: '  سىز ھىگگىس بوزونى ھەققىدە ئاڭلىغانمۇ؟ ئۇ ئالەمنىڭ سىرلىرىنى ئېچىشنىڭ ئاچقۇچى دېيىلىدۇ. بۇ زەررىچىنى ئادەتتىكى كىشىلەرنىڭ چۈشىنىشى تەس. بۇ قېتىم بىز ئۇنى ئىمكانقەدەر ئاددىي چۈشەندۈرۈپ بېرىمىز.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog79'
  },
  {   
    id: 78,
    title: ' كائىناتنىڭ كەلگۈسى نېمە؟ ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئالەمشۇناسلىق ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://i.pinimg.com/originals/29/65/26/29652645bfe64e65f453810ea6b48d67.gif',
    summary: '  ئالەمىمىز چوڭ پارتلاشتا بارلىققا كەلگەن ۋە كېڭىيىشنى داۋاملاشتۇرماقتا. ئۇنىڭ كەلگۈسى ئالەمدىكى ماددا مىقدارىغا باغلىق: ئوچۇق (چەكسىز كېڭىيىش) ياكى يېپىق (قىسقىراش).     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog78'
  },
  {   
    id: 77,
    title: ' كائىناتنىڭ يېشى قانچە؟ ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئالەمشۇناسلىق ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://erepublic.brightspotcdn.com/dims4/default/1272bd0/2147483647/strip/true/crop/480x270+0+0/resize/840x473!/quality/90/?url=http%3A%2F%2Ferepublic-brightspot.s3.us-west-2.amazonaws.com%2F9d%2F5b%2F593929c0a1fd1950e9f1beb3ab26%2Fnasa-black-hole-giphy.gif',
    summary: '  بىزنىڭ ئالەمىمىز ئارىلىققا ماس كېلىدىغان سۈرئەتتە كېڭىيىۋاتىدۇ. بۇ كېڭىيىش سۈرئىتى «ھەببول تۇراقلىقى» دەپ ئاتىلىدۇ. بۇ تۇراقلىقىنى بىلسەك، ئالەمنىڭ قاچان كېڭىيىشكە باشلىغانلىقىنى، يەنى ئۇنىڭ يېشىنى بېكىتەلەيمىز.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog77'
  },
  {   
    id: 76,
    title: ' كائىناتنىڭ ئاخىرى بارمۇ؟ ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئالەمشۇناسلىق ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://i.pinimg.com/originals/19/39/59/193959e347745645326f8928b807aa24.gif',
    summary: '   چەكلىك، ئەمما ئاخىرى يوق. مەركىزى، ئەمما ھېچقانداق نۇقتا مەركىزى ئەمەس.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog76'
  },
  {   
    id: 75,
    title: ' كائىنات تارىخى: چوڭ پارتلاش نەزەرىيىسى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئالەمشۇناسلىق ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://scitechdaily.com/images/Vast-Universe-Concept.gif',
    summary: '   بىز ئالەمنىڭ بىر زامانلار كىچىك، ئىنتايىن قىزىق ئوت توپى ئىكەنلىكىنى تەسەۋۋۇر قىلالايمىز. بۇ ئوت توپى پارتلاش خاراكتېرلىك كېڭىيىشكە باشلىغاندا ئالەمىمىز ياسالغان. بۇ ھادىسە «چوڭ پارتلاش» (Big Bang) دەپ ئاتىلىدۇ. «Big» — چوڭ، «Bang» — پارتلاش.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog75'
  },
  {   
    id: 74,
    title: '   LSTM ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  نىرۋاتورى  ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://miro.medium.com/v2/resize:fit:1400/0*KhHCSln2LmiFGH8r.gif',
    summary: '   RNN ۋە LSTM نى ئىشلىتىش ئاسان، لېكىن ئۇلارنىڭ ئىچكى مېخانىزىمىنى چۈشىنسىڭىز، تېخىمۇ ئۈنۈملۈك ئىشلىتەلەيسىز.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog74'
  },
  {   
    id: 73,
    title: '   كائىناتشۇناسلىقنىڭ ئەڭ چوڭ سىرى',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئالەمشۇناسلىق ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://i.pinimg.com/originals/58/ad/fd/58adfd04843697c9578d7ab172676274.gif',
    summary: '   1929-يىلى ئامېرىكىلىق ئاستروفىزىكا ئالىمى ئېدوىن خابل ئالەمنىڭ كېڭىيىۋاتقانلىقىنى بايقىغان.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog73'
  },
  {   
    id: 72,
    title: 'Black Hole    قارا ئۆڭكۈر: كائىناتشۇناسلىقنىڭ ئەڭ چوڭ سىرى',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  ئالەمشۇناسلىق ',
    tags: ['  تەرەققىيات', ' ئىلىم  ', '  كائىنات ', '  قارا ئۆڭكۇر '],
    image: 'https://cdn.mos.cms.futurecdn.net/MyWvcUrvDJJHPPu6LtbQTT.gif',
    summary: '     قارا ئۆڭكۈر — تارتىش كۈچى شۇنچە كۈچلۈككى،ھەتتا نۇرمۇ قېچىپ كېتەلمەيدىغان جىسىم. ھېچقانداق نۇر قېچىپ كېتەلمىگەچكە، بۇ جىسىم پۈتۈنلەي قارا رەڭدە كۆرۈنىدۇ — شۇڭا «قارا ئۆڭكۈر» دەپ ئاتالغان.    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog72'
  },
  {   
    id: 71,
    title: ' دروندىن خەرىتە ئىشلەش (Drone Mapping) نى باشتىن-ئاخىر ئۈگىنىڭ: تولۇق دەرسلىك (باشلانغۇچلار ئۈچۈن) ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  مەلۇمات ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  زىرەك ئۇچقۇ'],
    image: 'https://bbgeomatics.com/wp-content/uploads/2023/09/drone_mapping_juxtapose3.gif',
    summary: '                    دروندىن يۈكسەكتىن نۇرغۇن سۈرەت تارتىپ، كومپيۇتېر پروگراممىسى ئارقىلىق بۇ سۈرەتلەرنى بىرلەشتۈرۈپ، تۈز خەرىتە (Orthomosaic)، 3D مودېل، نۇقتا بۇلۇتى (Point Cloud) ۋە يۈسۈملۈك خەرىتىسى (DEM/DSM) ياساش ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog71'
  },
  {   
    id: 70,
    title: ' تىتانىك بىلەن سانلىق مەلۇمات ئىلمىنى ئۆگىنىش  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  مەلۇمات ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://miro.medium.com/v2/resize:fit:1000/1*wTzJQM1KNMQVImjXQRD9sw.gif',
    summary: '                     كىرىش سۆز - سانلىق مەلۇمات ئارقىلىق دۇنيانى كۆرۈش ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog70'
  },
  {   
    id: 69,
    title: ' Python دېتال كۆرۈنۈش ماستەر دەرىجىسى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  مەلۇمات ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://miro.medium.com/max/2148/1*oeK4EpsQx8S2h5D-J-x-BQ.gif',
    summary: '                       فيزىكا، ئالگورىزىم، تېخنىكا بىلەن بىرلەشتۈرۈلگەن زامانىۋى ئىلمىي ئىنقىلاب ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog69'
  },
  {   
    id: 68,
    title: '  تار تېئورىيىسى (String Theory)  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: [ ' string   ', '  يىپ ', '  كىۋانىت'],
    image: 'https://i.redd.it/a1fuo3dv75pc1.gif',
    summary: '                     كىملىكنىڭ ئاخىرقى تېئورىيىسى - ھەممە نەرسەنى بىرلەشتۈرۈش ئۈمىدى  ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog68'
  },
  {   
    id: 67,
    title: '  كىۋانت ماشىنا ئۆگىنىش يول خەرىتىسى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' ماشىنا ئۈگنىش  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://miro.medium.com/max/1948/0*St4Q17pUxJKDd022.png',
    summary: '                     2024-2026 | تولۇق يول يېتەكلەش ۋە مەنبەلەر ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog67'
  },
  {   
    id: 66,
    title: '  2026-يىللىق كەلگۈسى كەسىپلەر  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  سۇنئي ئەقىل',
    tags: ['  تەرەققىيات', ' سۇنئى ئەقىل  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://storiesbuzz.co.uk/wp-content/uploads/2025/12/AI-skills-that-will-be-most-valuable-in-2026.jpg',
    summary: '                    AI دەۋرىدە تاللاش قىلىش - «بىلىم + سۈنئىي ئەقىل + ئىجادىيەت»  ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog66'
  },
  {   
    id: 65,
    title: '  Quantum Machine Learning  كىۋانىت كومپيۇتېر ۋە كىۋانىت ماشىنا ئۆگىتىشنىڭ كىرىشى  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://miro.medium.com/1*T8s5bhYSTis71WSXJ8qcXA.gif',
    summary: ' ئالاھىدە ھالەت (Suoerposition), چىرمىشىش (Entanglement), ۋە چۈشۈرۈش (Measurement) قاتارلىق كىۋانىت ئىنكاسىلىرىنى پايدىلىنىپ، كلاسسىك كومپيۇتېرلارنىڭ ھەل قىلالمايدىغان مەسىلىلەرنى يېشىش مۇمكىن بولىدىغان ئۈسكۈنە. ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog65'
  },
  {   
    id: 64,
    title: '  سىزىقلىق ئالگېبرا ئاساسلىرى   ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://miro.medium.com/v2/resize:fit:1400/1*bUkIy7MDWd_gyft_6Dt_jg.gif',
    summary: '                   ۋېكتور دېگەنلىك — ئۇزۇنلۇقى (چوڭلۇقى) ۋە يۆنىلىشى بار بولغان چىزىق. مەسىلەن: سۈرئەت، كۈچ، تېزلىنىش قاتارلىق چوڭلۇقلار ۋېكتورلار بولۇپ ھېساپلىنىدۇ.',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog64'
  },
  {   
    id: 63,
    title: '  كۋانت كومپيۇتېر ئۇسۇللىرى ۋە ئاچقۇچلۇق سۆزلەر  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F183826%2F72c6decf-1323-949b-dc4a-28b77ceee93f.gif?ixlib=rb-4.0.0&auto=format&gif-q=60&q=75&s=9ab2cbb8d15b74e6b0746409bbc8de0c',
    summary: '                    كۋانت كومپيۇتېرلىقنىڭ ئاساسىي ئۇسۇللىرى ۋە مۇھىم تېرمىنلۇرلىرىغا ئومۇمىي كۆز قاراش ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog63'
  },
  {   
    id: 62,
    title: '  كۋانت چاستوتا ئۆزگەرتىش (QFC) نىڭ ئاساسىي پىرىنسىپلىرى ۋە ئەڭ يېڭى تەتقىقاتلار  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://miro.medium.com/0*9BQjPRHbtnycXWYD.gif',
    summary: '                      كۋانت تېخنىكىسى كەلگۈسىدىكى ئالاقە ۋە ھېسابلاش ساھەسىدە ئىنقىلاب پەيدا قىلىشى مۇمكىن. كۋانت چاستوتا ئۆزگەرتىش (QFC) ھەر خىل دولقۇن ئۇزۇنلۇقىدىكى فوتونلار (يورۇقلۇق زەررىچىلىرى) ئوتتۇرىسىدىكى كۋانت ئۇچۇرلىرىنى ئۆزگەرتىش تېخنىكىسى سۈپىتىدە دىققەتنى تارتماقتا ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog62'
  },
  {   
    id: 61,
    title: '  كۋانت كومپيۇتېرلىرى ۋە ماشىنا ئۆگىنىش: كۇتۇپخانىلارنى ئىشلىتىشتىكى ئەمەلىي مىساللار  ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://spectrum.ieee.org/media-library/leap-includes-demonstrations-of-how-classical-circuits-differ-from-their-quantum-equivalents.gif?id=25586793&width=1000&quality=85',
    summary: '                     كۋانت كومپيۇتېرلىرى تەرەققىي قىلغانسېرى، ئۇلارنىڭ ماشىنا ئۆگىنىش ساھەسىدە ئىشلىتىلىشى دىققەتنى تارتماقتا. ئادەتتىكى كومپيۇتېرلارغا سېلىشتۇرغاندا، كۋانت كومپيۇتېرلىرى بەزى ھېسابلاشلاردا زور سۈرئەتكە يېتىش ئىقتىدارىغا ئىگە ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog61'
  },
  {   
    id: 60,
    title: '  كۋانت ھېسابلاش: كەلگۈسى ھېسابلاشنىڭ يېڭى پارادىگمىسى   ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 1-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://images.cnbctv18.com/uploads/2025/05/quantum-computing-2025-05-f74cf40f93ddcda5d6ec16de64d86a42-1024x576.jpg',
    summary: '                       فيزىكا، ئالگورىزىم، تېخنىكا بىلەن بىرلەشتۈرۈلگەن زامانىۋى ئىلمىي ئىنقىلاب ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog60'
  },
  {   
    id: 59,
    title: '   كۋانت ماشىنا ئۆگىنىشى    ',
    author: 'قاۋۇلجان',
    date: '2026-يىلى 1-ئاينىڭ 2-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  ئالگورىزىملار'],
    image: 'https://physics.aps.org/assets/10.1103/Physics.17.s41/figure/1/large',
    summary: '                        كۋانت ھېسابلاش ۋە سۈنئىي ئەقىلنىڭ كەسپىي ئۇچرىشىشى',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog59'
  },
  {   
    id: 58,
    title: '  PennyLane دا كۋانت توك يوللىرىنى قانداق كۆرۈنۈشكە بولىدۇ؟   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://media.licdn.com/dms/image/v2/D5622AQHT92q0IOBTvQ/feedshare-shrink_800/feedshare-shrink_800/0/1686057052960?e=2147483647&v=beta&t=Rjc1Yn2IqsBxZjOig_HO8uCYBW5ax9m8Zed5V0pvfno',
    summary: '                       PennyLane دا كۈچلۈك كۆرۈنۈش تېخنىكىسى',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog58'
  },
  {   
    id: 57,
    title: '   Python سانلىق مەلۇمات كۆرۈنۈش ماستېر كۇرسى   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 1-ئاينىڭ 3-كۈنى',
    readTime: ' 11 مىنۇت',
    category: '  پايسان ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', '  '],
    image: 'https://img.freepik.com/free-vector/infographics-sci-fi-isolated-transparent-futuristic-background-abstract-future-concept-science-virtual-graphic-interface-screen-with-colored-infographic-digital-illustration_1150-55192.jpg?semt=ais_hybrid&w=740&q=80',
    summary: '                          «دۇنيادىكى ئەڭ ئاسان ماشىنا ئۆگىنىش پروگرامما تۈزۈش قوللانمىسى» ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog57'
  },
  {   
    id: 56,
    title: '  كۋانت ماشىنا ئۆگىنىشنى قانداق باشلاش كېرەك؟   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: [' ماشىنا ئۈگنىش  ', '  كەلگۈسى ', '  كىۋانىت'],
    image: 'https://cdn.prod.website-files.com/639a397b9711984d91a35d74/646bb9231ae54d62b77830a7_Quantum-Machine-Learning-p-2000.jpg',
    summary: '                         ماشىنا ئۆگىنىش قىزىقارلىق بولسا، كۋانت ماشىنا ئۆگىنىش (QML) ئۇنىڭدىن ئىككى قېتىم قىزىقارلىق!',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog56'
  },
  {   
    id: 55,
    title: '   «كۋانت ماشىنا ئۆگىنىش» مائارىپ مەزمۇنى   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: 'مائارىپ',
    tags: ['  تەرەققىيات', ' مائارىپ  ', '  كەلگۈسى ', ' كىۋانىت '],
    image: 'https://thequantuminsider.com/wp-content/uploads/2024/02/QuantumClassroom.webp',
    summary: '                        ئۇيغۇر كۋانت مائارىپىغا تۆھپە قوشۇش مەقسىتىدە',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog55'
  },
  {   
    id: 54,
    title: '  ئاساسلىق تەركىب ئانالىزى (PCA) — سانلىق مەلۇماتنى «ئوق بويىچە قىسقىرتىش» تېخنىكىسى   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: 'مائارىپ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  PCA ', ' ئاساسى تەركىپ ئانالىزى '],
    image: 'https://towardsdatascience.com/wp-content/uploads/2022/01/1Q5eINhZ7re-LHTESfJAB7A.gif',
    summary: '                        سانلىق مەلۇماتنى چۈشىنىش، كۆرۈش ۋە بىر تەرەپ قىلىشنى ئاسانلاشتۇرۇش ئۈچۈن ئىشلىتىلىدىغان ئىلغار تېخنىكا ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog54'
  },
  {   
    id: 53,
    title: '   PyTorch ئارقىلىق ماشىنا ئۆگىنىشنى سىستېماتىك ئۆگىنىش   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' پايسان ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://skillup.online/_next/image/?url=https%3A%2F%2Fcourses.skillup.online%2Fasset-v1%3AIBM%2BAI0112EN%2Bv1%2Btype%40asset%2Bblock%40Classification_with_PyTorch.png&w=3840&q=75',
    summary: '                         چوڭقۇر ئۆگىنىش مودېللىرىنى قۇرۇش، تەربىيەلەش ۋە باھالاش ئۈچۈن كۈچلۈك كۈتۈپخانا',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog53'
  },
  {   
    id: 52,
    title: '   GeoAI: بوشلۇق سانلىق مەلۇمات + سۈنئىي ئەقىل = جۇغراپىيىلىك زىرەك   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://registration.geospatialworld.net/event-blogs-portal/wp-content/uploads/2024/01/GIS-And-AI-1-1.png',
    summary: '                         GeoAI: بوشلۇق سانلىق مەلۇمات + سۈنئىي ئەقىل = جۇغراپىيىلىك زېرە ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog52'
  },
  {   
    id: 51,
    title: '   RAG توغرىسىدا قىسقىچە تەتقىقات — يېڭى ئۆگەنگۈچىلەرگە يېتەكچىلىك   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' سۇنئىي ئەقىل',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://learnopencv.com/wp-content/uploads/2024/04/rag-with-llms-1.gif',
    summary: '                          «دۇنيادىكى ئەڭ ئاسان ماشىنا ئۆگىنىش پروگرامما تۈزۈش قوللانمىسى» ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog51'
  },
  {   
    id: 50,
    title: '   ماشىنا ئۆگىنىش ماتىماتكىىسىسىغا كىرىش 2    ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://content.codecademy.com/courses/deeplearning-with-tensorflow/deep-learning-math/Matrix_B.gif',
    summary: '                          «دۇنيادىكى ئەڭ ئاسان ماشىنا ئۆگىنىش پروگرامما تۈزۈش قوللانمىسى» ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog50'
  },
  {   
    id: 49,
    title: '   ماشىنا ئۆگىنىش ماتىماتكاسى    ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://miro.medium.com/v2/resize:fit:1400/1*a46Tz42Epfu3ysFnvWpzWQ.gif',
    summary: '                          «دۇنيادىكى ئەڭ ئاسان ماشىنا ئۆگىنىش پروگرامما تۈزۈش قوللانمىسى» ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog49'
  },
  {   
    id: 48,
    title: '   رەڭلەر دۈنياسىغا سەپەر    ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://media.wired.com/photos/59325675aef9a462de9820bf/191:100/w_1280,c_limit/tumblr_nmnf2ezgHS1uojhbvo1_1280.gif',
    summary: '                          «دۇنيادىكى ئەڭ ئاسان رەڭ ئۆگىنىش   قوللانمىسى» ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog48'
  },
  {   
    id: 47,
    title: '   ماشىنا ئۆگىنىش كىرىشى    ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGe3vMe3dnSqjPftDs0vEL6xUz9BjNZ6CfaA&s',
    summary: '                          «دۇنيادىكى ئەڭ ئاسان ماشىنا ئۆگىنىش پروگرامما تۈزۈش قوللانمىسى» ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog47'
  },
  {   
    id: 46,
    title: '     ھەتتا 6 ياشلىق بالا چۈشىنىدۇ!؟ فىزىكىغا كىرىش 1-قىسىم',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://stickmanphysics.com/wp-content/uploads/2019/09/PMDroppedBallStickMan.gif',
    summary: '                            نيۇتون، «يورۇقلۇقنىڭ ھەقىقىي تەبىئىتى» ۋە «نىسپىيلىك نەزەرىيىسى» نىڭ شانلىق «مۇقەددىمىسى»     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog46'
  },
    {   
    id: 45,
    title: '     ئۇيغۇر سانلىق مەلۇمات مەركىزى (Data Center) قۇرۇشنىڭ كەلگۈسى  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' مەلۇمات  ', '  كەلگۈسى ', ' سۇنئىي ئەقىل'],
    image: 'https://substackcdn.com/image/fetch/$s_!tRiJ!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb0210c5a-68e9-427c-b9c9-accbddb7238b_500x281.gif',
    summary: '              سانلىق مەلۇمات مەركىزى — زور مىقداردىكى سانلىق مەلۇماتلارنى يىغىش، ساقلاش، ئىشلىتىش، تەھلىل قىلىش ۋە بىخەتەر باشقۇرۇش ئۈچۈن مەخسۇس قۇرۇلغان تېخنىكىلىق ئۇل ئەسلىھە مەجمۇئىدۇر.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog45'
  },
   {   
    id: 44,
    title: '       مور قانۇنى ئارقىلىق نامايان قىلىندى ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', ' ئەقىل'],
    image: 'https://media.rabbisacks.org/20211123150147/CHAOS-THEORY-GIF.gif',
    summary: '                 سۈنئىي ئەقىل - كەلگۈسىنىڭ تېخنىكىسى. بۇ بەت سىزنى AI دۇنياسىغا ئېلىپ بارىدۇ.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog44'
  },
   {   
    id: 43,
    title: '      6G: «تېز سۈرئەتلىك 5G» ئەمەس — «كەلگۈسى جەمئىيىتىنىڭ مەشغۇلات سىستېمىسى» ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', ' ئەقىل'],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1H99npI08vCXq-4jcZE9yBa5AMzBecJnGPw&s',
    summary: '         6G «تېز سۈرئەتلىك 5G» ئەمەس. «ئۈستۈنلۈك ئۈچۈن كۈرەش» ۋە 6G تەرەققىياتىنىڭ ئارقىسىدىكى «رەقەملىك قوشكېزەكلەر» نىڭ ئارزۇسى.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog43'
  },
   {   
    id: 42,
    title: '      نېمە ئۈچۈن كۋانت سىمۇلياتسىيەسى مۇھىم ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل كىۋانىت ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', ' ئەقىل'],
    image: 'https://www.quantamagazine.org/wp-content/uploads/2016/11/QuantumBrain_1300.gif',
    summary: '               كۋانت سىمۇلياتسىيەسى: قىيىن فىزىكىلىك سىستېمىلارنىڭ سانلىق دۇنياسى    ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog42'
  },
  {   
    id: 41,
    title: '      كۋانت دۇنياسىغا سەپەر',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل  ',
    tags: ['  كىۋانت', ' ئۈگنىش  ', '  كەلگۈسى ', ' كىۋانت مىخانىكىسى'],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ83fkvqCQ7ge8ykgMr_NIkxB7uUIWj6GIVRg&s',
    summary: '                 سۈنئىي ئەقىل - كەلگۈسىنىڭ تېخنىكىسى. بۇ بەت سىزنى AI دۇنياسىغا ئېلىپ بارىدۇ.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog41'
  },
  {   
    id: 40,
    title: '    قۇتادغۇبلىك ھەققىدە ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 11 مىنۇت',
    category: ' ئەقىل  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', ' ئەقىل'],
    image: 'https://media.tenor.com/nuw4wdzugoEAAAAe/uyghur-uygur.png',
    summary: '                 سۈنئىي ئەقىل - كەلگۈسىنىڭ تېخنىكىسى. بۇ بەت سىزنى AI دۇنياسىغا ئېلىپ بارىدۇ.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog40'
  },
  {   
    id: 39,
    title: '    sunzi ئۇرۇش سەنئىتىنىڭ زامانىۋى قوللىنىلىشى  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: ' 12 مىنۇت',
    category: '  ئەقىل  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', ' ئەقىل'],
    image: 'https://i.pinimg.com/originals/12/08/c9/1208c9059855cda94288f670b85a37ab.gif',
    summary: '                 سۈنئىي ئەقىل - كەلگۈسىنىڭ تېخنىكىسى. بۇ بەت سىزنى AI دۇنياسىغا ئېلىپ بارىدۇ.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog39'
  },
   {   
    id: 38,
    title: '     what is AI سۇنئىي ئەقىل دىگەن نېمە؟  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: 'سۇنئىي ئەقىل  ',
    category: 'سۇنئىي ئەقىل  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', 'سۇنئىي ئەقىل'],
    image: 'https://cdn.dribbble.com/userupload/23731317/file/original-5eb2f9967073700b38a31280cc2c32e0.gif',
    summary: '                 سۈنئىي ئەقىل - كەلگۈسىنىڭ تېخنىكىسى. بۇ بەت سىزنى AI دۇنياسىغا ئېلىپ بارىدۇ.     ',
    likes: 198,
    comments: 7,
    views: 1990,
    component: 'Blog38'
  },
  {   
    id: 37,
    title: '      1927 نوبىل مۇكاپاتىغا سازاۋەر بولغان  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: 'كىۋانىت  ',
    category: 'كىۋانىت  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', 'سۇنئىي ئەقىل'],
    image: 'https://pbs.twimg.com/media/B1uRj2tCUAEdGak.jpg',
    summary: '                    29 ئۇلۇغ فىزىكا ئالىملىرى بىرلەشىپ، كىۋانت مېخانىكىسىنىڭ ئاساسىنى قۇردى. بۇ يىغىن فىزىكا تارىخىدىكى ئەڭ مۇھىم ۋەقەلەردىن بىرى بولۇپ قالدى.     ',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog37'
  },
  {   
    id: 36,
    title: '      EPR Paradox دېگەن نىمە؟  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: 'كىۋانىت  ',
    category: 'كىۋانىت  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', 'سۇنئىي ئەقىل'],
    image: 'https://i.ytimg.com/vi/2q-YRLsQWxE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCssOgdm3LmsOEJ-CZ454UxJsd8Tw',
    summary: '                           EPR Paradox — كىۋانت مېخانىكىسىدىكى ئەڭ مۇھىم ۋە ئەڭ تالاش-تارتىشلىق مەسىلىلەرنىڭ بىرى. ئۇ «كىۋانت فىزىكىسى تولۇق چۈشەندۈرۈش بېرەلەمدۇ.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog36'
  },
  {   
    id: 35,
    title: '      كۋانت مېخانىكىسى بىلەن پەلسەپە ئوتتۇرىسىدىكى مۇناسىۋەت توغرىسىدا  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: '12 مىنۇت',
    category: 'كىۋانىت  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', 'سۇنئىي ئەقىل'],
    image: 'https://miro.medium.com/v2/resize:fit:1000/1*OAKb3-3hOBMCCHKWU7_ANg.gif',
    summary: '                             «ئۇ دىنىي ياكى ئىلھام ئەمەس، پەقەت چۈشەندۈرۈش تالاش-تارتىشى»       كۋانت مېخانىكىسى بىلەن پەلسەپە ئوتتۇرىسىدىكى مۇناسىۋەت:.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog35'
  },
   {   
    id: 34,
    title: '   ئەڭ چۈشىنىشلىك ماشىنا ئۆگىنىش دەرسلىك ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: '12 مىنۇت',
    category: 'كىۋانىت  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', 'سۇنئىي ئەقىل'],
    image: 'https://www.kdnuggets.com/wp-content/uploads/mayo_deep_learning_key_terms_explained_CNN.gif',
    summary: '         ئەمەلىي پروگراممىلار ئارقىلىق ماشىنا ئۆگىنىشنىڭ ئومۇمىي جەھەتتىن چۈشىنىشكە ياردەم بېرىدىغان دەرسلىك .',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog34'
  },
  {   
    id: 33,
    title: '   يۇقىرى پەن-تېخنىكا ۋە ئىنسانىيەتنىڭ كەلگۈسى ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: '12 مىنۇت',
    category: 'كىۋانىت  ',
    tags: ['  تەرەققىيات', ' ئۈگنىش  ', '  كەلگۈسى ', 'سۇنئىي ئەقىل'],
    image: 'https://static.wixstatic.com/media/3cd83b_c84cd20ab5154391a48b4940cf0157e0~mv2.gif',
    summary: '          تېخنىكىلىق ئىلگىرىلەش ھەم ئىنسانىيەتنىڭ تەرەققىياتىغا تەسىر كۆرسىتىدۇ، ھەم كەلگۈسىنى قانداق قۇرۇشقا تەسىر كۆرسىتىدۇ. تۆۋەندە 2030-يىلغىچە بولىدىغان مۇھىم تېخنىكىلىق ئىلگىرىلەشلەر ۋە ئۇلارنىڭ تەسىرى توغرىسىدا مەلۇمات بېرىلىدۇ. .',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog33'
  },
   {   
    id: 32,
    title: '     كىۋانك كومىپيۇتېرى بىزنىڭ كۈندىلىك تۇرمۇشىمىزدىكى بەزى قىينچىلقنى ھەل قىلالايدۇ   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 21-كۈنى',
    readTime: '12 مىنۇت',
    category: 'كىۋانىت  ',
    tags: ['  كىۋانىت', ' ئۈگنىش  ', '   ', 'سۇنئىي ئەقىل'],
    image: 'https://hellofuture.orange.com/wp-content/uploads/sites/56/2021/04/06_De%CC%81fense.gif',
    summary: '           ،كىۋانك كومىپيۇتېرى بىزنىڭ كۈندىلىك تۇرمۇشىمىزنىڭ بەش چوڭ قىينچلىقنى ھەل قىلالايدۇ .',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog32'
  },
  {   
    id: 31,
    title: '       Machine Learning with scikit-learn in Python - ماشنا ئۆگىنىش  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 21-كۈنى',
    readTime: '12 مىنۇت',
    category: 'سۇنئىي ئەقىل  ',
    tags: ['   ھەمكارلىق', ' ئۈگنىش  ', '   ', 'سۇنئىي ئەقىل'],
    image: 'https://www.polyu.edu.hk/its/-/media/department/its/events/2022/1/20220127-event-deep-learning-with-python_afternoon.gif?rev=10416606bfe943d5bfa1fdc02969cfa9&hash=8BA7B95906FE94B39E764F20F97A0909',
    summary: '           ،ماشىنا ئۈگنىش باشىلغۇچلار ئۇچۇن .',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog31'
  },
  {   
    id: 30,
    title: '       AI بىلەن    QKD دىن كېلىپ چىققان كىۋانىت ئىنتېرنېتىنىڭ فىزىكىلىق كىرگۈزۈشى ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 12-كۈنى',
    readTime: '12 مىنۇت',
    category: 'سۇنئىي ئەقىل , كىۋانىت',
    tags: ['   ھەمكارلىق', ' ئىنسانىيەت  ', '   ', 'سۇنئىي ئەقىل'],
    image: 'https://miro.medium.com/1*qkGMvnMz7YipxjZkr0Yhzw.gif',
    summary: '        كەلگۈسى تۇرمۇش يوللىرى - ئەمەلىيەت ئەھۋالى ۋە مۇۋەپپەقىيەتلىك ئەھۋاللار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog30'
  },
   {   
    id: 29,
    title: '       AI بىلەن ھەمكارلىشىش ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 12-كۈنى',
    readTime: '12 مىنۇت',
    category: 'سۇنئىي ئەقىل  ',
    tags: ['   ھەمكارلىق', ' ئىنسانىيەت  ', '   ', 'سۇنئىي ئەقىل'],
    image: 'https://media.licdn.com/dms/image/v2/D5612AQFv3mi9rIYfhw/article-cover_image-shrink_720_1280/B56ZWWzXu2HoAM-/0/1741991806557?e=2147483647&v=beta&t=jkhBH0v8Os9Kwqo4PEnHiSn6TYiFH6K_WXe4qoFyPRo',
    summary: '        كەلگۈسى تۇرمۇش يوللىرى - ئەمەلىيەت ئەھۋالى ۋە مۇۋەپپەقىيەتلىك ئەھۋاللار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog29'
  },
  {   
    id: 28,
    title: '     تۈركىيەنىڭ مۇۋەپپەقىيەتلىك QKD تەجرىبىسىنىڭ كۋانت تېخنىكىسى شىركەتلىرىگە تەسىرى ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 19-كۈنى',
    readTime: '11 مىنۇت',
    category: 'كىۋانىت  , مەخپىلەشتۇرش',
    tags: ['   ئالاقە', ' ئاچقۇچ تەقىسملەش  ', ' كىۋانىت  ', ' مەخپىلەشتۇرش'],
    image: 'https://media.licdn.com/dms/image/v2/D5622AQGDtI_78zIHkg/feedshare-shrink_800/B56ZojeepyH8Ag-/0/1761531793033?e=2147483647&v=beta&t=kw6WE-EpsUk8zFICfHTeOuEPcuAvp8u6iUZSjQINmXA',
    summary: '       تۈركىيەنىڭ چوڭ تېلېكوممۇنىكاتسىيە شىركىتى Turkcell ۋە شىۋىتسارىيەنىڭ ID Quantique (IDQ) شىركىتى ئىستانبۇلدا دۇنيادىكى تۇنجى قىتئەلەر ئارا كۋانت ئاچقۇچ تارقىتىش (QKD) نى مۇۋەپپەقىيەتلىك كۆرسەتتى.',
    likes: 137,
    comments: 7,
    views: 1900,
    component: 'Blog28'
  },
  {   
    id: 27,
    title: '      پايساندا كۋانت ئالگورىزىمىنى يولغا قويۇش ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 9-كۈنى',
    readTime: '11 مىنۇت',
    category: '   كىۋانىت',
    tags: ['   ئالگورىزم', ' پايسان  ', ' كىۋانىت  ', 'سۇنئىي ئەقىل'],
    image: 'https://miro.medium.com/v2/resize:fit:1400/0*1XAB1BL8Ee0rlkAj.jpg',
    summary: '         كۋانت ئۇچۇرى — كۋانت مېخانىكىسىنىڭ خۇسۇسىيەتلىرىنى ئۇچۇر بىر تەرەپ قىلىشتا ئىشلىتىدىغان ساھە.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog27'
  },
  {   
    id: 26,
    title: ' سۇنئي ئەقىل ۋە مائارىپ  5# ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل , مائارىپ',
    tags: ['   فىجىتال', ' مائارىپ  ', 'سۇنئىي ئەقىل'],
    image: 'https://epe.brightspotcdn.com/dims4/default/ad332a6/2147483647/strip/true/crop/3537x2400+32+0/resize/840x570!/quality/90/?url=https%3A%2F%2Fepe-brightspot.s3.us-east-1.amazonaws.com%2Ff1%2F6c%2F17d7d1bf4dc790e6b978b8a51f98%2Fai-age-appropriate-animated.gif',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog26'
  },
   {   
    id: 25,
    title: ' سۇنئي ئەقىل ۋە مائارىپ  4# ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل , مائارىپ',
    tags: ['   فىجىتال', ' مائارىپ  ', 'سۇنئىي ئەقىل'],
    image: 'https://www.the74million.org/wp-content/uploads/2023/08/artificial-intelligence-global-learning-c.gif',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog25'
  },
   {   
    id: 24,
    title: ' سۇنئي ئەقىل ۋە مائارىپ  3# ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 07-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل , مائارىپ',
    tags: ['   فىجىتال', ' مائارىپ  ', 'سۇنئىي ئەقىل'],
    image: 'https://epe.brightspotcdn.com/c4/fc/d41779074e15b3d8a634c61c8c29/ai-interview-animated.gif',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog24'
  },

  {   
    id: 23,
    title: ' سۇنئي ئەقىل ۋە مائارىپ   2# ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 11-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل , مائارىپ',
    tags: ['   فىجىتال', ' مائارىپ  ', 'سۇنئىي ئەقىل'],
    image: 'https://miro.medium.com/1*P6pZN5tEWasLc1JjvaZJYA.jpeg',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog23'
  },
  {   
    id: 22,
    title: ' سۇنئي ئەقىل ۋە مائارىپ   1# ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل , مائارىپ',
    tags: ['   فىجىتال', ' مائارىپ  ', 'سۇنئىي ئەقىل'],
    image: 'https://blogs.helloparent.com/wp-content/uploads/2024/06/importance-of-AI-in-education.jpg',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 197,
    comments: 5,
    views: 1990,
    component: 'Blog22'
  },
  {   
    id: 21,
    title: ' سۇنئي ئەقىل ۋە چوڭ مىڭە تەربىيەلەش ئارقىلىق ئىنسانىيەتنىڭ كەلگۈسىنى قايتا لايىھىلەش    ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل ',
    tags: ['ئۇچۇر بىر تەرەپ قىلىش', 'بالا بېقىش  ', 'ھەرىكەت كونترول قىلىش'],
    image: 'https://scitechdaily.com/images/Digital-Brain-Scan-AI-Analysis.gif',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog21'
  },
   {   
    id: 20,
    title: ' سۈنئىي ئەقىل بالا تەربىيەلەشنى مۇكەممەللەشتۈرىدىغان ۋە ئىنسانىيەتنىڭ تەرەققىياتىنى لايىھىلەيدىغان كەلگۈسى. ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل ',
    tags: ['ئۇچۇر بىر تەرەپ قىلىش', 'بالا بېقىش  ', 'ھەرىكەت كونترول قىلىش'],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyi7S8QA6Y3E5izO5dAv_vUgqD517lmUF_rw&s',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog20'
  },
  {   
    id: 19,
    title: '  سۈنئىي ئەقىلنىڭ كەلگۈسى ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'سۇنئىي ئەقىل ',
    tags: ['ئۇچۇر بىر تەرەپ قىلىش', 'ئەسلىمە ساقلىش', 'ھەرىكەت كونترول قىلىش'],
    image: 'https://www.tlciscreative.com/wp-content/uploads/2024/08/A.I-2.gif',
    summary: '            سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog19'
  },
  {   
    id: 18,
    title: '  كلاسسىك نەزەرىيە بىلەن كۋانت نەزەرىيىسىنىڭ بىرلىشىشى   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: ' فىزىكا  ',
    tags: ['كۋانت مەخپىيلىكى', 'كۋانت تەسەۋۋۇر', 'كۋانت ئاماللىرى'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/04/Quantum_entanglement_vs_classical_correlation_video.gif',
    summary: '                    فىزىكا دۇنياسىنىڭ ئىككى چوڭ ئېغىر تاشلىرى: كلاسسىك نەزەرىيە بىلەن كۋانت نەزەرىيىسىنىڭ «تىرلىشىشى»نىڭ ئۇسۇلى.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog18'
  },
  {   
    id: 17,
    title: '                 سۈنئىي ئەقىل بىلەن سۆھبەت 8-باب — كۋانت كومپيۇتېرلىرىنىڭ كەلگۈسى ۋە سۈنئىي ئەقىلنىڭ كەلگۈسى   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'AI كىۋانىت',
    tags: ['ئۇچۇر بىر تەرەپ قىلىش', 'ئەسلىمە ساقلىش', 'ھەرىكەت كونترول قىلىش'],
    image: 'https://www.epfl.ch/schools/sti/research-domains/wp-content/uploads/2024/02/quantum.gif',
    summary: '          كۋانت كومپيۇتېرىدا سۈنئىي ئەقىلنى ئىجرا قىلىشنىڭ قانداق ئىمكانىيەتلىرى بار.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog17'
  },
   {   
    id: 16,
    title: '     «ئەقىل» مېڭە تەرىپىدىن يارىتىلغان   ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'AI ئاخلاقى',
    tags: ['ئۇچۇر بىر تەرەپ قىلىش', 'ئەسلىمە ساقلىش', 'ھەرىكەت كونترول قىلىش'],
    image: 'https://scitechdaily.com/images/Left-Right-Brain-Signals.gif',
    summary: '      سۈنئىي ئەقىل «ئەقىل-بەدەن مەسىلىسى» نىڭ ئاخىرقى يەكۈنىنى ئاشكارىلايدۇ.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog16'
  },
  {   
    id: 15,
    title: '  138 مىليارد يىل ئىلگىرىكى چوڭ پارتىلاش',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'AI ئاخلاقى',
    tags: [' «خۇدا» دەرىجىدىكى AI نىڭ ياراتقان «ئەقىل پارتىلىشى» ئىدى'],
    image: 'https://www.universetoday.com/article_images/history.bigbang.jpg',
    summary: '      ئەقىل پارتىلىشى ۋە چوڭ پارتىلاش.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog15'
  },
   {   
    id: 14,
    title: '  138 مىليارد يىل ئىلگىرىكى چوڭ پارتىلاش',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'AI ئاخلاقى',
    tags: [' «خۇدا» دەرىجىدىكى AI نىڭ ياراتقان «ئەقىل پارتىلىشى» ئىدى'],
    image: 'https://www.universetoday.com/article_images/history.bigbang.jpg',
    summary: '      ئەقىل پارتىلىشى ۋە چوڭ پارتىلاش.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog14'
  },
  {   
    id: 13,
    title: 'يۇقىرى پەن-تېخنىكا ئەخلاقى',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '11 مىنۇت',
    category: 'AI ئاخلاقى',
    tags: [' «سەۋەپ-نەتىجە» ياكى «باھا». ياخشىلىق قىلساڭ ياخشى نەتىجە، يامانلىق قىلساڭ يامان نەتىجە قايتىدۇ. بۇ چوڭقۇر دىنىي ۋە ئەخلاقىي چۈشەنچىلەرنىڭ ئاساسىدىكى ساددە پىكىردۇر.'],
    image: 'https://aka-link.net/wp-content/uploads/2024/06/agi-asi-comparison07.jpg',
    summary: '                <ئاللاھنىڭ> ئورنىنى ئالىدىغان سۇنئي ئەقىلنىڭ سەۋەپ-نەتىجە سىستېمىسى» نى تەكشۈرۈش.',
    likes: 127,
    comments: 4,
    views: 1790,
    component: 'Blog13'
  },
  {   
    id: 12,
    title: '     يۇقىرى پەن-تېخنىكا ۋە ئۇيغۇرلار - لىكسىيە خۇلاسە',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 12-ئاينىڭ 3-كۈنى',
    readTime: '12 مىنۇت',
    category: 'تېخنكا ',
    tags: ['  بۇ لىكسىيە خۇلاسەسى 2025 يىلى ئۇيغۇر ياشلىرىنىڭ تېخنىكىۋى تەرەققىيات يولىدىكى ئەڭ مۇھىم يول خەرىتىسى ۋە پىلانى بولۇپ، ھەر بىر ئۇيغۇر ياشىنىڭ كەلگۈسىنى قۇرۇشىغا ياردەم بېرىشى مەقسەت قىلىندى.'],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQem8YnAxnnsttYcGNrtJwttGx-siaygj4XHQ&s',
    summary: '                AI، Quantum، Big Data دەۋرى — ئۇيغۇرلار ئۈچۈن ئەڭ چوڭ پۇرسەت ۋە ئەڭ چوڭ زاۋالنىڭ بۆلۈنۈش نۇقتىسى.',
    likes: 127,
    comments: 45,
    views: 1890,
    component: 'Blog12'
  },
  {    
    id: 10,
    title: 'كوانتۇم مېخانىكىسى 100 يىل',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 1-ئاينىڭ 3-كۈنى',
    readTime: '12 مىنۇت',
    category: 'AI كىۋانىت',
    tags: ['AI كىۋانىت', 'ئىلىم-پەن پىلىسۇپىيىسى', 'كىۋانىت چەكلىمىسى', 'كىۋانىت تېخنىكىسى'],
    image: 'https://cefir.org/wp-content/uploads/2025/04/lzbwekmvkh.jpg',
    summary: 'AI نېمە ئۈچۈن ئىلىم-پەن دۆلىتىدە «دەۋا قىلغۇچى مەنتىق» نى ياراتتى؟ بۇنىڭ ئارقا قىستىقىدا ياتقان ئادەم بىلەن AI نىڭ ئاساسىي قىممەت دىلىنىشىدىكى پەرق.',
    likes: 127,
    comments: 45,
    views: 1890,
    component: 'Blog10'
  },
    {
    id: 11,
    title: 'كىۋانىت ماشىنا ئۈگنىش  ',
    author: 'قاۋۇلجان',
    date: '2025-يىلى 1-ئاينىڭ 3-كۈنى',
    readTime: '12 مىنۇت',
    category: 'تېخنىكا ',
    tags: ['كىۋانىت ماشىنا ئۈگنىش ۋە كەلگۈسى تەرەققىيات'],
    image: 'https://media.licdn.com/dms/image/v2/D5612AQGSo_-36Dbthg/article-cover_image-shrink_720_1280/B56ZV0BTtDHQAI-/0/1741408255914?e=2147483647&v=beta&t=az-GV4Bxw4lsF2ioJXeMjHnxM8RYQp7pm4oa5DFJUVE',
    summary: ' كىۋانىت ماشىنا ئۈگنىشنىڭ ئاساسىي مەزمۇنى ۋە ئۇنىڭ AI تەرەققىياتىدىكى مۇھىم رولى ھەققىدە.',
    likes: 127,
    comments: 45,
    views: 1890,
    component: 'Blog11'
  },
  {
    id: 1,
    title: 'ئۇيغۇر ئۇسلۇبىدىكى زامانىۋى UI/UX لايىھىلەش',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 2-ئاينىڭ 15-كۈنى',
    readTime: '5 مىنۇت',
    category: 'تېخنىكا',
    tags: ['UI/UX', 'لايىھە', 'ئۇيغۇرچە', 'دىزايىن'],
    image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'ئۇيغۇر مەدەنىيىتىنىڭ بايلىقىنى قانداق زامانىۋى تېخنىكىلار بىلەن بىرلەشتۈرۈپ، ئەنسىز تەجرىبە يارىتالايمىز؟',
    likes: 245,
    comments: 34,
    views: 1500,
    component: 'Blog01'
  },
  {
    id: 2,
    title: 'ئۇيغۇر مۇزىكىسىنىڭ رەقەملىك ئەۋلادى',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 3-ئاينىڭ 20-كۈنى',
    readTime: '7 مىنۇت',
    category: 'مەدەنىيەت',
    tags: ['مۇزىكا', 'رەقەملىك', 'ئەنئەنى', 'AI'],
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'ئۇيغۇر مۇزىكىسى مىڭ يىللىق تارىخقا ئىگە بولۇپ، بۈگۈنكى رەقەملىك دەۋردە قانداق ساقلىنىپ، ياش نەسىللەرگە قانداق يەتكۈزۈلۈشى...',
    likes: 321,
    comments: 45,
    views: 2100,
    component: 'Blog02'
  },
  {
    id: 3,
    title: 'ئۇيغۇر رەسساملىق سەنئىتىنىڭ يېڭى دەۋرى',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 2-ئاينىڭ 5-كۈنى',
    readTime: '6 مىنۇت',
    category: 'سەنئەت',
    tags: ['نەقىش', 'دىجىتال', '3D', 'VR'],
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'دىجىتال تېخنىكا ئۇيغۇر رەسساملىق سەنئىتىگە يېڭى ھايات بەردى. بىز قەدىمكى نەقىش-ناۋا ئېلېمېنتلىرىنى قانداق زامانىۋى دىجىتال سەنئەتكە ئايلاندۇرالايمىز؟',
    likes: 189,
    comments: 28,
    views: 1750,
    component: 'Blog03'
  },
  {
    id: 4,
    title: 'ئۇيغۇر تىلىنىڭ رەقەملىك جەھەتتىكى ئىمكانىيىتى',
    author: 'قاۋۇلجان ئابدۇرېھىم',
    date: '2024-يىلى 1-ئاينىڭ 28-كۈنى',
    readTime: '8 مىنۇت',
    category: 'تىل',
    tags: ['تىل', 'AI', 'تېخنىكا', 'مەدەنىيەت'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'رەقەملىك دەۋر ئۇيغۇر تىلى ئۈچۈن پۇرسەت ۋە چەلگىلەرنى بىرلىكتە ئېلىپ كەلدى. بىز قانداق قىلىپ ئۇيغۇر تىلىنى رەقەملىك دۇنيادا كۈچلەندۈرەلەيمىز؟',
    likes: 312,
    comments: 52,
    views: 2300,
    component: 'Blog04'
  },
  {
    id: 5,
    title: 'ئۇيغۇر كىيىم-كەچەك دىزايىنىنىڭ زامانىۋىلىشىشى',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 3-ئاينىڭ 5-كۈنى',
    readTime: '6 مىنۇت',
    category: 'مودا',
    tags: ['كىيىم', 'دىزايىن', 'مودا', 'ئەنئەنى'],
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'ئۇيغۇر كىيىم-كەچەك دىزايىنىنىڭ ئەنئەنىۋى ئېلېمېنتلىرىنى قانداق زامانىۋى مودا بىلەن بىرلەشتۈرۈش...',
    likes: 156,
    comments: 23,
    views: 1250,
    component: 'Blog05'
  },
  {
    id: 6,
    title: 'ئۇيغۇر تائاملىرىنىڭ خەلقئارالىشىش يوللىرى',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 2-ئاينىڭ 22-كۈنى',
    readTime: '7 مىنۇت',
    category: 'مەدەنىيەت',
    tags: ['تائام', 'ئەنئەنى', 'تېخنىكا', 'ساغلاملىق'],
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'ئۇيغۇر تائاملىرىنى رەقەملىك تېخنىكا ئارقىلىق قانداق خەلقئارالىشىپ، دۇنياغا تونۇتۇش...',
    likes: 198,
    comments: 31,
    views: 1650,
    component: 'Blog06'
  },
  {
    id: 7,
    title: 'ئۇيغۇر ئارخىتېكتۇرا سەنئىتى ۋە دىجىتال نەسىل',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 1-ئاينىڭ 15-كۈنى',
    readTime: '9 مىنۇت',
    category: 'سەنئەت',
    tags: ['بىنا', 'ئارخىتېكتۇرا', '3D', 'دىجىتال'],
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'ئۇيغۇر ئارخىتېكتۇرا سەنئىتىنى دىجىتال تېخنىكا ئارقىلىق قانداق ساقلاش ۋە تەرەققىي قىلدۇرۇش...',
    likes: 267,
    comments: 38,
    views: 1950,
    component: 'Blog07'
  },
  {
    id: 8,
    title: 'ئۇيغۇرچە ئەپلەرنىڭ تەرەققىياتى ۋە كەلگۈسى',
    author: ' قاۋۇلجان',
    date: '2024-يىلى 3-ئاينىڭ 1-كۈنى',
    readTime: '8 مىنۇت',
    category: 'تېخنىكا',
    tags: ['ئەپ', 'موبىل', 'تېخنىكا', 'ئۇيغۇرچە'],
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    summary: 'ئۇيغۇرچە ئەپلەرنىڭ تەرەققىيات خەرىتىسى ۋە كەلگۈسىدىكى ئىمكانىيەتلەر...',
    likes: 234,
    comments: 41,
    views: 1800,
    component: 'Blog08'
  },
  {
    id: 9,
    title: 'ئۇيغۇر خەت-سەنئىتىنىڭ دىجىتال ئىپادىسى',
    author: ' خەلق',
    date: '2024-يىلى 2-ئاينىڭ 28-كۈنى',
    readTime: '5 مىنۇت',
    category: 'سەنئەت',
    tags: ['خەت', 'سەنئەت', 'دىجىتال', 'فونت'],
    image: 'https://akademiye.org/en/wp-content/uploads/2013/05/ata-ana.jpg',
    summary: 'ئۇيغۇر خەت-سەنئىتىنى دىجىتال دۇنياغا قانداق ماسلاشتۇرۇش ۋە تارقىتىش...',
    likes: 178,
    comments: 26,
    views: 1450,
    component: 'Blog09'
  }
];

export const categories = [
  'ھەممىسى',
  'تېخنىكا', 
  'مەدەنىيەت',
  'سەنئەت',
  'تىل',
  'مودا',
  'AI ئاخلاقى',
  'AI كىۋانىت',
 'سۇنئىي ئەقىل  ',
  'پەلسەپە ',
  'فىزىكا  ',
  'مائارىپ',
  'كىۋانىت  ',
];

// ئۇيغۇرچە date نى parse قىلىش فۇنكسىيىسى (خاتالىقنى ئالدى ئەلىش ئۈچۈن)
const parseUyghurDate = (dateStr) => {
  const match = dateStr.match(/(\d{4})-يىلى\s+(\d{1,2})-ئاينىڭ\s+(\d{1,2})-كۈنى/);
  if (match) {
    const [, year, month, day] = match;
    return new Date(parseInt(year), parseInt(month) - 1, parseInt(day));  // JS Date: month 0-dىن باشلىنىدۇ
  }
  return new Date(0);  // Default: 1970-01-01، sort نى بۇزمايدۇ
};

// ئۇستەل ئۇچۇرلىرى
export const blogStats = {
  totalPosts: BLOG_POSTS.length,
  totalViews: BLOG_POSTS.reduce((sum, post) => sum + post.views, 0),
  totalLikes: BLOG_POSTS.reduce((sum, post) => sum + post.likes, 0),
  totalComments: BLOG_POSTS.reduce((sum, post) => sum + post.comments, 0),
  mostViewedPost: BLOG_POSTS.reduce((max, post) => post.views > max.views ? post : max, BLOG_POSTS[0]),
  mostLikedPost: BLOG_POSTS.reduce((max, post) => post.likes > max.likes ? post : max, BLOG_POSTS[0]),
  mostCommentedPost: BLOG_POSTS.reduce((max, post) => post.comments > max.comments ? post : max, BLOG_POSTS[0])
};

// ئايلانما ماقالىلەر
export const featuredPosts = [
  BLOG_POSTS[0], // AI نىڭ «تۈگۈن» ۋە ئادەمنىڭ «قىممىتى»
  BLOG_POSTS[1], // ئۇيغۇر ئۇسلۇبىدىكى زامانىۋى UI/UX لايىھىلەش
  BLOG_POSTS[3]  // ئۇيغۇر رەسساملىق سەنئىتىنىڭ يېڭى دەۋرى
];

// تېما بويىچە ئايرىش
export const postsByCategory = categories.slice(1).map(category => ({
  category,
  posts: BLOG_POSTS.filter(post => post.category === category),
  count: BLOG_POSTS.filter(post => post.category === category).length
}));

// ئاخىرقى ماقالىلەر (تۈزىتىلگەن: date parsing بىلەن sort)
export const recentPosts = [...BLOG_POSTS]
  .sort((a, b) => parseUyghurDate(b.date) - parseUyghurDate(a.date))
  .slice(0, 3);

// ئەڭ كۆپ كۆرۈلگەن ماقالىلەر
export const popularPosts = [...BLOG_POSTS]
  .sort((a, b) => b.views - a.views)
  .slice(0, 3);